### PR TITLE
Bugs and features

### PR DESCRIPTION
**Pull request by bobmcwhirter**

### CODE REVIEW

**Comment by lulf** [comment]
We can't really have newer embassy until we've converted the drivers using the now removed serial::{Read, Write} traits to use embedded-io traits. Shouldn't be that much work, I have a half-converted version that needs finishing.

**Comment by bobmcwhirter** [comment]
I think I’m taking it on. Maybe.

**Comment by lulf** [comment]
@bobmcwhirter You could use this commit as reference: https://github.com/drogue-iot/drogue-device/commit/61098bf8827a1ed8b8f05a24c2c330f7534de79d   

The drivers were in fact using AsyncBufRead and AsyncWrite before, but I switched them to using the serial traits since it made it possible to remove the additional command channel and removed some overhead using split TX and RX. With AsyncBufRead and AsyncWrite, we'd need to re-introduce the command queue and the associated overhead since the BufferedUart's don't support splitting into separate TX and RX.

So either:

1) Add split to embassy BufferedUarts (both nrf and stm32), in which case you can just switch to the new embedded-io traits from the serial traits (and adjust examples)

or

2) Refactor the drivers to use the command channel implementation referenced in the above commit. No changes needed in embassy, but driver is less efficient.

I'm fine with either choice, just thought I'd mention the options.

**Comment by bobmcwhirter** [comment]
I defer. Going to continue embedded-bt-mesh peeling out.

**Pull request closed without merging**
