### PR TITLE
Feature/issues 376 esp32 c3 devkitc 02 riscv support

### PR DESCRIPTION
**Pull request by elasticdotventures**
I've posted in #matrix, starting to map out the flow, 🙏🏻 asking for cooperation on planning and feedback. 

see also:
* https://github.com/esp-rs/esp-hal/pull/834
* https://github.com/embassy-rs/embassy/pull/1978

### CODE REVIEW

**Review by lulf — COMMENTED** [review]
I think this approach looks good (assuming the boards with a README only is in the works?)

I'm not sure the llvm-Risc_V stuff belongs here, though I'm happy to be convinced otherwise. They are just simulation boards?

**Review by MabezDev — CHANGES_REQUESTED** [review]
* The esp32c3 doesn't have SAADC, UARTE or TWISPI. 
* Many of the imports are completely incorrect. 
* embassy_esp32 doesn't exist. 
* There is no embassy config for esp chips yet.

This needs a lot more work before its mergable.

**Comment by elasticdotventures** [comment]
https://www.espressif.com/sites/default/files/documentation/esp32-c3-wroom-02_datasheet_en.pdf
@MabezDev .. 🤔 from the datasheet:

ESP32-C3 has a 32-bit RISC-V single-core processor. It integrates a rich set of peripherals, ranging from UART,
I2C, I2S, remote control peripheral, LED PWM controller, general DMA controller, TWAI® controller, USB
Serial/JTAG controller, temperature sensor, ADC, etc. It also includes SPI, Dual SPI and Quad SPI
interfaces

as far as "this needs work" .. yep. chatgpt wrote that, it's a strawman to get feedback.  I gave it both a C3 and S2 data sheet and let it spit out a quick first draft.  At the last point I hadn't even found the esp-rs examples.  Yes - I'm probably the least qualified person to do this, but also planning to use this embassy + drogue-iot code in an upcoming project(s) and so it'll get use and the bugs will get sorted. 

At a broader level - I'm trying to decide if it would be best to build an  "embassy_esp32" (in embassy) that abstract the differences & unifies the similiarties between the each esp32 HAL (like the embassy_stm32 does), with quick sketch to see the differences between supporting c3 / s2, .. or just build against a specific board for each HAL, and/or for risc-v + qemu, both for non-espressif boards (with espressif chips), and other embedded-rs risc-v silicon (i.e. siFive).    

I would really appreciate your thoughts on this topic.  also cc: @lulf

**Comment by MabezDev** [comment]
> At a broader level - I'm trying to decide if it would be best to build an "embassy_esp32" (in embassy) that abstract the differences & unifies the similiarties between the each esp32 HAL (like the embassy_stm32 does), with quick sketch to see the differences between supporting c3 / s2, .. or just build against a specific board for each HAL, and/or for risc-v + qemu, both for non-espressif boards (with espressif chips), and other embedded-rs risc-v silicon (i.e. siFive).

The above comment is out of scope for a Drogue BSP package, its probably better to discuss this on the hal. With that said, eventually, it will be a unified hal, see: https://github.com/esp-rs/esp-hal/issues/446.

**Pull request closed without merging**
