### PR TITLE
*WIP* Rethink

### PR DESCRIPTION
**Pull request by lulf**
As discussed, rethink examples and device

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
The board profile stuff?

**Comment by lulf** [comment]
@bobmcwhirter Yes, it's very early and not  even fancy, I just want to check if I can get CI working with it. Example app here that works with two different boards: 

https://github.com/drogue-iot/drogue-device/tree/rethink/examples/blinky/src

The binding is done within each example, because as we discussed, it is dependent on the application, so why not just have the mapping in Rust. It feels maybe a bit artificial for the blinky example, but I hope to have an example with networking to drogue cloud working for different boards, which will be a better test to see if it's worthwhile.

I think if we want to provide a more generic approach where examples don't bundle the board mappings, an alternative is to decide on a enumeration scheme for pins and buttons and do the mapping in drogue-device. But my impression from our discussions is that we didn't want to got that way?

What is 'magical' is that drogue-device can 'inject' the memory.x linker script for the appropriate board. I plan to use this for bundling the bootloader with examples as well, using some OTA client in the example that works with any board providing the network capability for that example.

I'm also experimenting using xtask as a utility to flash/debug the device, possibly better done in an external tool but for now it's easier to keep it there.

For flashing, one can go to the repo root folder and run:

```
# Headless flash
cargo xtask flash nrf52-dk examples/blinky

# Attach RTT
cargo xtask debug nrf52-dk examples/blinky
```

**Comment by lulf** [comment]
@bobmcwhirter Two variants now:

* Board variants and definitions contained within each example: https://github.com/drogue-iot/drogue-device/blob/rethink/examples/blinky/src/main.rs
** ➕ No board-specific or HAL dependency needed in drogue-device, which means we can probably release drogue-device since other embassy dependencies are released
** ➖ Requires maintaining a per-board mapping for every example. So if we have many cross-board examples: more maintenance overhead.
** ➖ Doing a filesystem copy of an example for your board gives you lot of stuff for other boards you 'dont need'. This could be made simpler with an xtask command for cloning.

* Board variants and a generic "Device" trait in drogue-device: https://github.com/drogue-iot/drogue-device/blob/rethink/examples/blinky-generic/src/main.rs
** ➕ Examples don't need to define a mapping, handle the absence of the required device at run time
** ➖ Requires per-board code and HAL dependency in drogue-device
** ➖ Flexible pins for SPI, I2C makes it very complex. The lowest common denominator is clearly lower than for the first variant.

**Comment by lulf** [comment]
Ok, I got another idea that I'm not sure is doable or not, but I think it's heading in the right direction from the usage POV:

```
//-----------------------------------
// These traits are defined in drogue-device and will have an implementation for boards that can support them.
pub trait Blinkable: Sized {
    type Led: embedded_hal::digital::OutputPin;
    fn led(&mut self) -> Self::Led;
}

pub trait Pressable: Sized {
    type Button: embedded_hal::digital::InputPin + embedded_hal_async::digital::Wait;
    fn button(&mut self) -> Self::Button;
}

pub trait Connectable: Sized {
    type Network: embedded_nal_async::TcpConnect;
    fn network(&mut self) -> Self::Network;
}
//END -----------------------------------

// Macro that can locate the implementations of the above traits for a board that
// was selected at compile time. Is this possible? If selected board does not have an implementation, cannot be done. Otherwise, yay?
#[derive(Blinkable, Pressable)]
pub struct MyDevice;

// Macro that creates the device and provides it to the application, should be simple if the device is derive-able.
#[drogue_device::main]
async fn main(device: MyDevice, _s: embassy_executor::Spawner) {
    let mut led = device.led();
    let mut button = device.button();
    loop {
        button.wait_for_any_edge().await;
        if button.is_low() {
            led.set_high();
        } else {
            led.set_low();
        }
    }
}
```

**Comment by lulf** [comment]
I decided on a different approach:

* Use existing structure because it makes it easier to reuse examples externally.
* Focus on IoT, remove non-IoT examples
* Add BSPs for supported boards and use it in examples

**Pull request closed without merging**
