### PR TITLE
WIP - stm32f4 esp8266 example

### PR DESCRIPTION
**Pull request by jcrossley3**
I'd like to pick up where I left off on this once @lulf helps me with a `BufferedUarte` or equivalent for stm32

### CODE REVIEW

**Comment by lulf** [comment]
@jcrossley3 I spent last week trying to shaping the nRF buffered uart into something that could be used for stm32 as well, but in retrospect I think I started in the wrong end here. I also have a different STM32 board, so I would need to port one for my own board first. 

Given that there is so many changes coming to STM32 in embassy, I will change my strategy to build on the stm32-neo work that @bobmcwhirter is already doing for STM32 and make that work with my board (STM32L0) first.

Might take a bit longer, but probably a better approach in the long run.

**Comment by jcrossley3** [comment]
Sounds good to me @lulf. I fared no better exploring the latest knative eventing/faas stuff this week than I did on the stm32 example. :)

**Comment by lulf** [comment]
@jcrossley3 Ok, good news. There is now a buffered uart example with wifi _and_ TLS now: https://github.com/drogue-iot/drogue-device/tree/main/examples/stm32h7/nucleo-h743zi/esp8266

Adapting this to your F4 shouldn't bee much more than changing pins and embassy features in Cargo.toml.

**Comment by lulf** [comment]
@jcrossley3 I've created a rebased version of this branch in #116 that uses the not-yet-merged buffered embassy usart for your board. I've made it use the 'drogue-temperature' example application, so it should work out of the box with drogue cloud. I've left the TLS bits as an exercise for the reader :)  But the other examples give you an idea of how to do TLS.

**Pull request closed without merging**
