### PR TITLE
Enable defmt feature on embedded-update

### PR DESCRIPTION
**Pull request by matoushybl**

### CODE REVIEW

**Review by lulf — APPROVED** [review]
Thank you! 

bors r+

**Comment by lulf** [comment]
@matoushybl maybe you can run cargo xtask update and commit the repo state after that?

**Comment by matoushybl** [comment]
Sorry, I didn't have time to fix the PR. It should be fixed now.

**Comment by lulf** [comment]
Thanks!

bors r+

**Pull request merged**
