### PR TITLE
Add workflow badges for CI build and test

### PR DESCRIPTION
**Pull request by danbev**
This commit adds badges for the CI build.yaml and test.yaml workflow
as the current badge (ci.yaml) does not exist any more.

### CODE REVIEW

**Comment by lulf** [comment]
Great, thank you!

bors r+

**Comment by danbev** [comment]
@lulf Would you be able to re-run the merge job? 
(I ran the failing `std/cloud ` example locally which passed so perhaps this was just a glitch). Thanks

**Comment by danbev** [comment]
Sorry, I realized that I ran the wrong test locally :disappointed:. I'll take a closer look at this tomorrow.

**Comment by lulf** [comment]
I think the test is due to some errors on the sandbox service. I'll merge this now, and look into the sandbox issue tomorrow. Thanks!

**Pull request merged**
